# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "L'étude des crédits budgétaires : un reflet du contrôle parlementaire"
email: francois@fmgagnon.com
description: > # this means to ignore newlines until "baseurl:"
  Un essai sur l'évolution du contrôle parlementaire à travers le processus annuel d'étude des crédits en commission.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://etudedescredits.fmgagnon.com" # the base hostname & protocol for your site
twitter_username: fmgagnon

# Build settings
markdown: kramdown
